project_id = "mgnawkfmfbwzpjiilhcf"

[functions.shark-ai]
verify_jwt = false

[functions.property-valuation]
verify_jwt = false

[functions.mercado-pago-checkout]
verify_jwt = false

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.asaas-checkout]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false
