INSERT INTO public.system_options (category, value, sort_order) VALUES
  ('tipo_imovel', 'Condomínio', 9),
  ('tipo_proprietario', 'Construtora', 1),
  ('tipo_proprietario', 'Investidor', 2),
  ('tipo_proprietario', 'Particular', 3),
  ('tipo_proprietario', 'Adm Comercial', 4),
  ('tipo_proprietario', 'Exclusividade', 5),
  ('condicoes_pagamento', 'À Vista', 1),
  ('condicoes_pagamento', 'Parcelamento 12x', 2),
  ('condicoes_pagamento', 'Parcelamento 24x', 3),
  ('condicoes_pagamento', 'Parcelamento 36x', 4),
  ('condicoes_pagamento', 'Parcelamento 48x', 5),
  ('condicoes_pagamento', 'Parcelamento 60x', 6),
  ('condicoes_pagamento', 'Parcelamento 120x', 7),
  ('condicoes_pagamento', 'Financiamento Bancário', 8),
  ('condicoes_pagamento', 'FGTS', 9),
  ('condicoes_pagamento', 'Dação', 10),
  ('condicoes_pagamento', 'Permuta', 11),
  ('condicoes_pagamento', 'Consórcio', 12),
  ('tipo_condominio', 'Vertical', 1),
  ('tipo_condominio', 'Horizontal', 2),
  ('tipo_condominio', 'Misto', 3),
  ('tipo_empreendimento', 'Residencial', 1),
  ('tipo_empreendimento', 'Comercial', 2),
  ('tipo_empreendimento', 'Misto', 3),
  ('tipo_empreendimento', 'Loteamento', 4),
  ('status_empreendimento', 'Lançamento', 1),
  ('status_empreendimento', 'Em construção', 2),
  ('status_empreendimento', 'Pronto', 3),
  ('status_empreendimento', 'Em vendas', 4),
  ('status_edificio', 'Lançamento', 1),
  ('status_edificio', 'Em construção', 2),
  ('status_edificio', 'Pronto', 3)
ON CONFLICT (category, value) DO NOTHING;
